Question 1 in Lab 2 Exercise


In [3]:
import numpy as np

In [4]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
print(array.shape)

(10,)


In [5]:
arr1 = np.random.random(20)
print('Array with random values')
# Variance :  represents the dispersion or spread of a set of data points around their mean (average).
sample_variance = np.var(arr1, ddof=1)
print(f'Sample Variance {sample_variance}')
print(f'Variance with random values : {np.var(arr1)}')

print(f'Mean with random values : {np.mean(arr1)}')

Array with random values
Sample Variance 0.06535131244390142
Variance with random values : 0.06208374682170635
Mean with random values : 0.5778614792975636


In [ ]:
# for variance
print('Array with Specified values')
print(f'Sample Variance {np.var(array, ddof=1)}')
print(f'Variance : {np.var(array)}')
print(f'Mean : {np.mean(array)}')

Question 2 in Lab 2 Exercise

In [6]:
x = np.random.random(8)
y = np.random.random(8)

print(x)
print(y)

cov_mat = np.stack((x, y), axis=0)
# Here we take two, one dimensional array so we have to combine both the arrays for that we using the stack() function
print('\nCoavriance of a matrix : (x,y)\n')
print(np.cov(cov_mat))

print(f'\nShape of covariance matrix is {np.shape(cov_mat)}')


[0.76027336 0.99524598 0.45804332 0.4736893  0.47769188 0.96424598
 0.3236538  0.26742954]
[0.53709774 0.50717653 0.19104589 0.48823756 0.89510272 0.04595416
 0.20686794 0.20776482]

Coavriance of a matrix : (x,y)

[[0.07883189 0.00134801]
 [0.00134801 0.07494816]]

Shape of covariance matrix is (2, 8)


In [7]:
randArr = np.random.random((3,3))
# Here we initiallly creating a 3X3 matrix so we can directly calculate the covariance of the matrix by passing it to the cov() function
#Co-variance:   indicates the extent to which two variables change together.
print(np.cov(randArr))
print(f'\nShape of covariance matrix is {np.shape(randArr)}')

[[ 0.06232104 -0.0328963   0.04085896]
 [-0.0328963   0.01917488 -0.02574864]
 [ 0.04085896 -0.02574864  0.0364439 ]]

Shape of covariance matrix is (3, 3)


Question 3 in Lab 2 Exercise

In [ ]:
# For Corelation
# np.correlate() is designed to work with 1D arrays, and when you pass it a 2D array, it doesn't know how to compute the correlation properly.
arr1 = np.random.random(10)
arr2 = np.random.random(10)
#Corelation :  describes the extent to which two variables move in relation to each other
print(arr1)
print(arr2)
print(np.correlate(arr1, arr2))

Question 4 in Lab 2 Exercise

In [ ]:
# Generate a random MxN matrix
feature_matrix = np.random.random((5, 10))
print("Feature Matrix (MxN):")
print(feature_matrix)

# Compute the Covariance Matrix
covariance_matrix = np.cov(feature_matrix)
print("\nCovariance Matrix (MxM):")
print(covariance_matrix)

# Compute the Correlation Matrix
correlation_matrix = np.corrcoef(feature_matrix)
print("\nCorrelation Matrix (MxM):")
print(correlation_matrix)